<?php
namespace common\components;
use yii\base\Component;
use yii\base\Exception;
use Yii;
use yii\db\Query;
use \PHPMailer;
use yii\db\Expression;
use ZipArchive;
use kartik\export\ExportMenu;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class CommonUtility extends Component {
    
    /**
     * This function will fetch data from API.
     *
     * @author Amol Koli
     * @param $url = String,
     * @return Array
     *
     */
	public function doCurl($url){
		$curl = curl_init();
		curl_setopt($curl, CURLOPT_URL, $url);
		curl_setopt($curl, CURLOPT_HEADER, false);
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
		//curl_setopt($curl, CURLOPT_HTTPHEADER, array("Cookie: APIC-cookie=" . $token));
		curl_setopt($curl, CURLOPT_FAILONERROR, 1);
		$result = curl_exec($curl);     
		return json_decode($result,true);
	}

    public function exportData($dataProvider, $gridColumns, $title) {
        return ExportMenu::widget([
            'dataProvider' => $dataProvider,
            'columns' => $gridColumns,
            'target' => ExportMenu::TARGET_SELF,
            'dropdownOptions' => [
                'label' => 'Export',
                'class' => 'btn btn-success btn-sm',
            ],
            'columnSelectorOptions' => [],
            'showColumnSelector' => FALSE,
            'fontAwesome' => true,
            'formatter' => [
                'class' => 'yii\i18n\Formatter',
                'nullDisplay' => '-',
            ],
            'exportConfig' => [
                ExportMenu::FORMAT_HTML => false,
                ExportMenu::FORMAT_TEXT => false,
                ExportMenu::FORMAT_PDF => false,
                ExportMenu::FORMAT_EXCEL => false,
            ],
            'filename' => $title . '_' . time(),
            'showConfirmAlert' => false
        ]);
    }

    //Yii::$app->commonUtility->getCountryDropdown()
    public function getCountryDropdown() 
    {
        $countryArray = [
            ['name' => 'Afghanistan', 'value' => 'Afghanistan'],
            ['name' => 'Aland Islands', 'value' => 'Aland Islands'],
            ['name' => 'Albania', 'value' => 'Albania'],
            ['name' => 'Algeria', 'value' => 'Algeria'],
            ['name' => 'American Samoa', 'value' => 'American Samoa'],
            ['name' => 'Andorra', 'value' => 'Andorra'],
            ['name' => 'Angola', 'value' => 'Angola'],
            ['name' => 'Anguilla', 'value' => 'Anguilla'],
            ['name' => 'Antarctica', 'value' => 'Antarctica'],
            ['name' => 'Antigua & Barbuda', 'value' => 'Antigua & Barbuda'],
            ['name' => 'Argentina', 'value' => 'Argentina'],
            ['name' => 'Armenia', 'value' => 'Armenia'],
            ['name' => 'Aruba', 'value' => 'Aruba'],
            ['name' => 'Ascension Island', 'value' => 'Ascension Island'],
            ['name' => 'Australia', 'value' => 'Australia'],
            ['name' => 'Austria', 'value' => 'Austria'],
            ['name' => 'Azerbaijan', 'value' => 'Azerbaijan'],
            ['name' => 'Bahamas', 'value' => 'Bahamas'],
            ['name' => 'Bahrain', 'value' => 'Bahrain'],
            ['name' => 'Bangladesh', 'value' => 'Bangladesh'],
            ['name' => 'Barbados', 'value' => 'Barbados'],
            ['name' => 'Belarus', 'value' => 'Belarus'],
            ['name' => 'Belgium', 'value' => 'Belgium'],
            ['name' => 'Belize', 'value' => 'Belize'],
            ['name' => 'Benin', 'value' => 'Benin'],
            ['name' => 'Bermuda', 'value' => 'Bermuda'],
            ['name' => 'Bhutan', 'value' => 'Bhutan'],
            ['name' => 'Bolivia', 'value' => 'Bolivia'],
            ['name' => 'Bosnia & Herzegovina', 'value' => 'Bosnia & Herzegovina'],
            ['name' => 'Botswana', 'value' => 'Botswana'],
            ['name' => 'Bouvet Island', 'value' => 'Bouvet Island'],
            ['name' => 'Brazil', 'value' => 'Brazil'],
            ['name' => 'British Indian Ocean Territory', 'value' => 'British Indian Ocean Territory'],
            ['name' => 'British Virgin Islands', 'value' => 'British Virgin Islands'],
            ['name' => 'Brunei', 'value' => 'Brunei'],
            ['name' => 'Bulgaria', 'value' => 'Bulgaria'],
            ['name' => 'Burkina Faso', 'value' => 'Burkina Faso'],
            ['name' => 'Burundi', 'value' => 'Burundi'],
            ['name' => 'Cambodia', 'value' => 'Cambodia'],
            ['name' => 'Cameroon', 'value' => 'Cameroon'],
            ['name' => 'Canada', 'value' => 'Canada'],
            ['name' => 'Canary Islands', 'value' => 'Canary Islands'],
            ['name' => 'Cape Verde', 'value' => 'Cape Verde'],
            ['name' => 'Caribbean Netherlands', 'value' => 'Caribbean Netherlands'],
            ['name' => 'Cayman Islands', 'value' => 'Cayman Islands'],
            ['name' => 'Central African Republic', 'value' => 'Central African Republic'],
            ['name' => 'Ceuta & Melilla', 'value' => 'Ceuta & Melilla'],
            ['name' => 'Chad', 'value' => 'Chad'],
            ['name' => 'Chile', 'value' => 'Chile'],
            ['name' => 'China', 'value' => 'China'],
            ['name' => 'Christmas Island', 'value' => 'Christmas Island'],
            ['name' => 'Clipperton Island', 'value' => 'Clipperton Island'],
            ['name' => 'Cocos Islands', 'value' => 'Cocos Islands'],
            ['name' => 'Colombia', 'value' => 'Colombia'],
            ['name' => 'Comoros', 'value' => 'Comoros'],
            ['name' => 'Congo (DRC)', 'value' => 'Congo (DRC)'],
            ['name' => 'Congo (Republic)', 'value' => 'Congo (Republic)'],
            ['name' => 'Cook Islands', 'value' => 'Cook Islands'],
            ['name' => 'Costa Rica', 'value' => 'Costa Rica'],
            ['name' => 'Cote d’Ivoire', 'value' => 'Cote d’Ivoire'],
            ['name' => 'Croatia', 'value' => 'Croatia'],
            ['name' => 'Cuba', 'value' => 'Cuba'],
            ['name' => 'Curacao', 'value' => 'Curacao'],
            ['name' => 'Cyprus', 'value' => 'Cyprus'],
            ['name' => 'Czech Republic', 'value' => 'Czech Republic'],
            ['name' => 'Denmark', 'value' => 'Denmark'],
            ['name' => 'Diego Garcia', 'value' => 'Diego Garcia'],
            ['name' => 'Djibouti', 'value' => 'Djibouti'],
            ['name' => 'Dominica', 'value' => 'Dominica'],
            ['name' => 'Dominican Republic', 'value' => 'Dominican Republic'],
            ['name' => 'Ecuador', 'value' => 'Ecuador'],
            ['name' => 'Egypt', 'value' => 'Egypt'],
            ['name' => 'El Salvador', 'value' => 'El Salvador'],
            ['name' => 'Equatorial Guinea', 'value' => 'Equatorial Guinea'],
            ['name' => 'Eritrea', 'value' => 'Eritrea'],
            ['name' => 'Estonia', 'value' => 'Estonia'],
            ['name' => 'Ethiopia', 'value' => 'Ethiopia'],
            ['name' => 'Falkland Islands', 'value' => 'Falkland Islands'],
            ['name' => 'Faroe Islands', 'value' => 'Faroe Islands'],
            ['name' => 'Fiji', 'value' => 'Fiji'],
            ['name' => 'Finland', 'value' => 'Finland'],
            ['name' => 'France', 'value' => 'France'],
            ['name' => 'French Guiana', 'value' => 'French Guiana'],
            ['name' => 'French Polynesia', 'value' => 'French Polynesia'],
            ['name' => 'French Southern Territories', 'value' => 'French Southern Territories'],
            ['name' => 'Gabon', 'value' => 'Gabon'],
            ['name' => 'Gambia', 'value' => 'Gambia'],
            ['name' => 'Georgia', 'value' => 'Georgia'],
            ['name' => 'Germany', 'value' => 'Germany'],
            ['name' => 'Ghana', 'value' => 'Ghana'],
            ['name' => 'Gibraltar', 'value' => 'Gibraltar'],
            ['name' => 'Greece', 'value' => 'Greece'],
            ['name' => 'Greenland', 'value' => 'Greenland'],
            ['name' => 'Grenada', 'value' => 'Grenada'],
            ['name' => 'Guadeloupe', 'value' => 'Guadeloupe'],
            ['name' => 'Guam', 'value' => 'Guam'],
            ['name' => 'Guatemala', 'value' => 'Guatemala'],
            ['name' => 'Guernsey', 'value' => 'Guernsey'],
            ['name' => 'Guinea', 'value' => 'Guinea'],
            ['name' => 'Guinea-Bissau', 'value' => 'Guinea-Bissau'],
            ['name' => 'Guyana', 'value' => 'Guyana'],
            ['name' => 'Haiti', 'value' => 'Haiti'],
            ['name' => 'Heard & McDonald Islands', 'value' => 'Heard & McDonald Islands'],
            ['name' => 'Honduras', 'value' => 'Honduras'],
            ['name' => 'Hong Kong', 'value' => 'Hong Kong'],
            ['name' => 'Hungary', 'value' => 'Hungary'],
            ['name' => 'Iceland', 'value' => 'Iceland'],
            ['name' => 'India', 'value' => 'India'],
            ['name' => 'Indonesia', 'value' => 'Indonesia'],
            ['name' => 'Iran', 'value' => 'Iran'],
            ['name' => 'Iraq', 'value' => 'Iraq'],
            ['name' => 'Ireland', 'value' => 'Ireland'],
            ['name' => 'Isle of Man', 'value' => 'Isle of Man'],
            ['name' => 'Israel', 'value' => 'Israel'],
            ['name' => 'Italy', 'value' => 'Italy'],
            ['name' => 'Jamaica', 'value' => 'Jamaica'],
            ['name' => 'Japan', 'value' => 'Japan'],
            ['name' => 'Jersey', 'value' => 'Jersey'],
            ['name' => 'Jordan', 'value' => 'Jordan'],
            ['name' => 'Kazakhstan', 'value' => 'Kazakhstan'],
            ['name' => 'Kenya', 'value' => 'Kenya'],
            ['name' => 'Kiribati', 'value' => 'Kiribati'],
            ['name' => 'Kosovo', 'value' => 'Kosovo'],
            ['name' => 'Kuwait', 'value' => 'Kuwait'],
            ['name' => 'Kyrgyzstan', 'value' => 'Kyrgyzstan'],
            ['name' => 'Laos', 'value' => 'Laos'],
            ['name' => 'Latvia', 'value' => 'Latvia'],
            ['name' => 'Lebanon', 'value' => 'Lebanon'],
            ['name' => 'Lesotho', 'value' => 'Lesotho'],
            ['name' => 'Liberia', 'value' => 'Liberia'],
            ['name' => 'Libya', 'value' => 'Libya'],
            ['name' => 'Liechtenstein', 'value' => 'Liechtenstein'],
            ['name' => 'Lithuania', 'value' => 'Lithuania'],
            ['name' => 'Luxembourg', 'value' => 'Luxembourg'],
            ['name' => 'Macau', 'value' => 'Macau'],
            ['name' => 'Macedonia', 'value' => 'Macedonia'],
            ['name' => 'Madagascar', 'value' => 'Madagascar'],
            ['name' => 'Malawi', 'value' => 'Malawi'],
            ['name' => 'Malaysia', 'value' => 'Malaysia'],
            ['name' => 'Maldives', 'value' => 'Maldives'],
            ['name' => 'Mali', 'value' => 'Mali'],
            ['name' => 'Malta', 'value' => 'Malta'],
            ['name' => 'Marshall Islands', 'value' => 'Marshall Islands'],
            ['name' => 'Martinique', 'value' => 'Martinique'],
            ['name' => 'Mauritania', 'value' => 'Mauritania'],
            ['name' => 'Mauritius', 'value' => 'Mauritius'],
            ['name' => 'Mayotte', 'value' => 'Mayotte'],
            ['name' => 'Mexico', 'value' => 'Mexico'],
            ['name' => 'Micronesia', 'value' => 'Micronesia'],
            ['name' => 'Moldova', 'value' => 'Moldova'],
            ['name' => 'Monaco', 'value' => 'Monaco'],
            ['name' => 'Mongolia', 'value' => 'Mongolia'],
            ['name' => 'Montenegro', 'value' => 'Montenegro'],
            ['name' => 'Montserrat', 'value' => 'Montserrat'],
            ['name' => 'Morocco', 'value' => 'Morocco'],
            ['name' => 'Mozambique', 'value' => 'Mozambique'],
            ['name' => 'Myanmar', 'value' => 'Myanmar'],
            ['name' => 'Namibia', 'value' => 'Namibia'],
            ['name' => 'Nauru', 'value' => 'Nauru'],
            ['name' => 'Nepal', 'value' => 'Nepal'],
            ['name' => 'Netherlands', 'value' => 'Netherlands'],
            ['name' => 'New Caledonia', 'value' => 'New Caledonia'],
            ['name' => 'New Zealand', 'value' => 'New Zealand'],
            ['name' => 'Nicaragua', 'value' => 'Nicaragua'],
            ['name' => 'Niger', 'value' => 'Niger'],
            ['name' => 'Nigeria', 'value' => 'Nigeria'],
            ['name' => 'Niue', 'value' => 'Niue'],
            ['name' => 'Norfolk Island', 'value' => 'Norfolk Island'],
            ['name' => 'Northern Mariana Islands', 'value' => 'Northern Mariana Islands'],
            ['name' => 'North Korea', 'value' => 'North Korea'],
            ['name' => 'Norway', 'value' => 'Norway'],
            ['name' => 'Oman', 'value' => 'Oman'],
            ['name' => 'Pakistan', 'value' => 'Pakistan'],
            ['name' => 'Palau', 'value' => 'Palau'],
            ['name' => 'Palestine', 'value' => 'Palestine'],
            ['name' => 'Panama', 'value' => 'Panama'],
            ['name' => 'Papua New Guinea', 'value' => 'Papua New Guinea'],
            ['name' => 'Paraguay', 'value' => 'Paraguay'],
            ['name' => 'Peru', 'value' => 'Peru'],
            ['name' => 'Philippines', 'value' => 'Philippines'],
            ['name' => 'Pitcairn Islands', 'value' => 'Pitcairn Islands'],
            ['name' => 'Poland', 'value' => 'Poland'],
            ['name' => 'Portugal', 'value' => 'Portugal'],
            ['name' => 'Puerto Rico', 'value' => 'Puerto Rico'],
            ['name' => 'Qatar', 'value' => 'Qatar'],
            ['name' => 'Reunion', 'value' => 'Reunion'],
            ['name' => 'Romania', 'value' => 'Romania'],
            ['name' => 'Russia', 'value' => 'Russia'],
            ['name' => 'Rwanda', 'value' => 'Rwanda'],
            ['name' => 'Samoa', 'value' => 'Samoa'],
            ['name' => 'San Marino', 'value' => 'San Marino'],
            ['name' => 'Sao Tome & Principe', 'value' => 'Sao Tome & Principe'],
            ['name' => 'Saudi Arabia', 'value' => 'Saudi Arabia'],
            ['name' => 'Senegal', 'value' => 'Senegal'],
            ['name' => 'Serbia', 'value' => 'Serbia'],
            ['name' => 'Seychelles', 'value' => 'Seychelles'],
            ['name' => 'Sierra Leone', 'value' => 'Sierra Leone'],
            ['name' => 'Singapore', 'value' => 'Singapore'],
            ['name' => 'Sint Maarten', 'value' => 'Sint Maarten'],
            ['name' => 'Slovakia (Slovensko)', 'value' => 'Slovakia (Slovensko)'],
            ['name' => 'Slovenia (Slovenija)', 'value' => 'Slovenia (Slovenija)'],
            ['name' => 'Solomon Islands', 'value' => 'Solomon Islands'],
            ['name' => 'Somalia', 'value' => 'Somalia'],
            ['name' => 'South Africa', 'value' => 'South Africa'],
            ['name' => 'South Georgia & South Sandwich Islands', 'value' => 'South Georgia & South Sandwich Islands'],
            ['name' => 'South Korea', 'value' => 'South Korea'],
            ['name' => 'South Sudan', 'value' => 'South Sudan'],
            ['name' => 'Spain', 'value' => 'Spain'],
            ['name' => 'Sri Lanka', 'value' => 'Sri Lanka'],
            ['name' => 'St. Barthelemy', 'value' => 'St. Barthelemy'],
            ['name' => 'St. Helena', 'value' => 'St. Helena'],
            ['name' => 'St. Kitts & Nevis', 'value' => 'St. Kitts & Nevis'],
            ['name' => 'St. Lucia', 'value' => 'St. Lucia'],
            ['name' => 'St. Martin', 'value' => 'St. Martin'],
            ['name' => 'St. Pierre & Miquelon', 'value' => 'St. Pierre & Miquelon'],
            ['name' => 'St. Vincent & Grenadines', 'value' => 'St. Vincent & Grenadines'],
            ['name' => 'Sudan', 'value' => 'Sudan'],
            ['name' => 'Suriname', 'value' => 'Suriname'],
            ['name' => 'Svalbard & Jan Mayen', 'value' => 'Svalbard & Jan Mayen'],
            ['name' => 'Swaziland', 'value' => 'Swaziland'],
            ['name' => 'Sweden', 'value' => 'Sweden'],
            ['name' => 'Switzerland', 'value' => 'Switzerland'],
            ['name' => 'Syria', 'value' => 'Syria'],
            ['name' => 'Taiwan', 'value' => 'Taiwan'],
            ['name' => 'Tajikistan', 'value' => 'Tajikistan'],
            ['name' => 'Tanzania', 'value' => 'Tanzania'],
            ['name' => 'Thailand', 'value' => 'Thailand'],
            ['name' => 'Timor-Leste', 'value' => 'Timor-Leste'],
            ['name' => 'Togo', 'value' => 'Togo'],
            ['name' => 'Tokelau', 'value' => 'Tokelau'],
            ['name' => 'Tonga', 'value' => 'Tonga'],
            ['name' => 'Trinidad & Tobago', 'value' => 'Trinidad & Tobago'],
            ['name' => 'Tristan da Cunha', 'value' => 'Tristan da Cunha'],
            ['name' => 'Tunisia', 'value' => 'Tunisia'],
            ['name' => 'Turkey', 'value' => 'Turkey'],
            ['name' => 'Turkmenistan', 'value' => 'Turkmenistan'],
            ['name' => 'Turks & Caicos Islands', 'value' => 'Turks & Caicos Islands'],
            ['name' => 'Tuvalu', 'value' => 'Tuvalu'],
            ['name' => 'U.S. Outlying Islands', 'value' => 'U.S. Outlying Islands'],
            ['name' => 'U.S. Virgin Islands', 'value' => 'U.S. Virgin Islands'],
            ['name' => 'Uganda', 'value' => 'Uganda'],
            ['name' => 'Ukraine', 'value' => 'Ukraine'],
            ['name' => 'United Arab Emirates', 'value' => 'United Arab Emirates'],
            ['name' => 'United Kingdom', 'value' => 'United Kingdom'],
            ['name' => 'United States', 'value' => 'United States'],
            ['name' => 'Uruguay', 'value' => 'Uruguay'],
            ['name' => 'Uzbekistan', 'value' => 'Uzbekistan'],
            ['name' => 'Vanuatu', 'value' => 'Vanuatu'],
            ['name' => 'Vatican City', 'value' => 'Vatican City'],
            ['name' => 'Venezuela', 'value' => 'Venezuela'],
            ['name' => 'Vietnam', 'value' => 'Vietnam'],
            ['name' => 'Wallis & Futuna', 'value' => 'Wallis & Futuna'],
            ['name' => 'Western Sahara', 'value' => 'Western Sahara'],
            ['name' => 'Yemen', 'value' => 'Yemen'],
            ['name' => 'Zambia', 'value' => 'Zambia'],
            ['name' => 'Zimbabwe', 'value' => 'Zimbabwe'],
        ];
        return \yii\helpers\ArrayHelper::map($countryArray, 'name', 'value');
    }
	
}
